{
  try {
    is.reset();
    fail("IOException expected.");
  }
 catch (  IOException e) {
  }
}
