{
  simple2.throwExceptionOnNextUse=true;
  assertEquals("IOException on second stream should not affect at this time!",72,si.read());
  simple1.throwExceptionOnNextUse=true;
  try {
    si.read();
    fail("IOException not thrown!");
  }
 catch (  IOException e) {
  }
}
