{
  double[] x={0};
  boolean thrown=false;
  try {
    Array.setDouble(x,0,1);
  }
 catch (  Exception e) {
    fail("Exception during get test : " + e.getMessage());
  }
  assertEquals("Get returned incorrect value",1,Array.getDouble(x,0),0.0);
  try {
    Array.setDouble(new Object(),0,9);
  }
 catch (  IllegalArgumentException e) {
    thrown=true;
  }
  if (!thrown) {
    fail("Passing non-array failed to throw exception");
  }
  thrown=false;
  try {
    Array.setDouble(x,4,9);
  }
 catch (  ArrayIndexOutOfBoundsException e) {
    thrown=true;
  }
  if (!thrown) {
    fail("Invalid index failed to throw exception");
  }
  thrown=false;
  try {
    Array.setDouble(null,0,0);
  }
 catch (  NullPointerException e) {
    thrown=true;
  }
  if (!thrown) {
    fail("Null argument failed to throw NPE");
  }
}
