{
  String errorMessage="This is an error message";
  try {
    if (true)     throw new ConcurrentModificationException(errorMessage);
  }
 catch (  ConcurrentModificationException e) {
    assertTrue("Exception thrown without error message",e.getMessage().equals(errorMessage));
    return;
  }
  fail("Failed to throw expected ConcurrentModificationException");
}
