{
  if (throwExceptionOnNextUse) {
    throw new IOException("Exception thrown for testing purpose.");
  }
}
