{
  try {
    Method mth=TestMethod.class.getMethod("voidMethod",new Class[0]);
    Class[] ex=mth.getExceptionTypes();
    assertEquals("Returned incorrect number of exceptions",1,ex.length);
    assertTrue("Returned incorrect exception type",ex[0].equals(IllegalArgumentException.class));
    mth=TestMethod.class.getMethod("intMethod",new Class[0]);
    ex=mth.getExceptionTypes();
    assertEquals("Returned incorrect number of exceptions",0,ex.length);
  }
 catch (  Exception e) {
    fail("Exception during getExceptionTypes: " + e.toString());
  }
}
